### ISSUE TITLE
Possible bug in countdown.js

### ISSUE THREAD

**Issue by skandhurkat** [inlieuoffun/inlieuoffun.github.io#11]
[Line 77](https://github.com/inlieuoffun/inlieuoffun.github.io/blob/ed45c71d44b6b4403ced7de9d707eb83a8b9857d/assets/countdown.js#L77) has an incorrect nesting of the `if(diff.hours < 5)`, should be `if(diff.days == 0 && diff.hours < 5)`.

Haven't seen it in action yet, so I could be wrong. :)

**Comment by skandhurkat** [comment]
Debugging in the console, I was able to trigger the issue.

![image](https://user-images.githubusercontent.com/1826881/96658637-e39ff600-12f9-11eb-935c-782b84e99400.png)

**Comment by creachadair** [comment]
Thanks very much for the report, and especially for the hands-on debugging. This is addressed in #12.
