### ISSUE TITLE
Episode 219

### ISSUE THREAD

**Issue by mcdy** [inlieuoffun/inlieuoffun.github.io#13]
Lisa Page joins Episode 219 on camera (18m 08s into the [Crowdcast recording](https://www.crowdcast.io/e/in-lieu-of-fun-episode-113)). Not sure how you'd want that reflected on the Guest List / Episode Log.

**Comment by creachadair** [comment]
As a general rule I don't attribute people as guests for Saturday, but this case is interesting and special enough to deserve an exception. Done in bedfc763.
