### ISSUE TITLE
Episode 220

### ISSUE THREAD

**Issue by mcdy** [inlieuoffun/inlieuoffun.github.io#14]
Attribution for the idea behind Episode 220 (Scott Shapiro and Sarah Longwell)
https://twitter.com/ActPeacefully/status/1321656187033591810

Ben's acknowledgment
https://twitter.com/benjaminwittes/status/1321787362762842113

**Comment by creachadair** [comment]
Thank you for tracking that down. As a general rule, I have not made any organized effort to keep track of who suggested specific episodes, and would prefer not to have to. Most episodes aren't suggested by anyone, and those which are often have multiple plausible candidates. Unlike guest and topic records, I'm not convinced this information is of general interest to most viewers.

On that basis, the lack of explicit attributions is as-intended. That said, if you have a compelling case to the contrary, and are interested in owning the effort of collecting the data, I'm receptive to counter-proposals.

**Comment by mcdy** [comment]
I don't feel strongly about this one way or the other. I only log something here if one of the hosts outright mentions the attribution during the show itself. Happy to refrain from similar future posts.

**Comment by creachadair** [comment]
Just to be clear: I don't want to discourage you from filing issues—I just wanted to clarify my reasoning on this topic. Please feel free to make whatever suggestions you think are appropriate. 🙂

**Comment by mcdy** [comment]
Copy that, appreciate the clarification. 🙏🏼
