### ISSUE TITLE
Countdown is broken

### ISSUE THREAD

**Issue by skandhurkat** [inlieuoffun/inlieuoffun.github.io#16]
At 15:50 UTC on Nov 3, the countdown shows 5 h ago.

![image](https://user-images.githubusercontent.com/1826881/98008366-4dfc7000-1da9-11eb-93ef-43b0e075116c.png)

**Comment by skandhurkat** [comment]
I misunderstood the countdown, it is to polls open, not polls close :)

**Comment by creachadair** [comment]
As you observed, it was originally until polls open, but now that the day is upon us, I updated it to (last) polls close.
