### ISSUE TITLE
Shopify miss-configured for store and merch redirects?

### ISSUE THREAD

**Issue by tomrake** [inlieuoffun/inlieuoffun.github.io#19]
###  From you main page there is a link

In the dotted box with   "ILoF Paraphernalia" at the top:

https://inlieuof.fun/store

It redirects to:

https://revolutionartshop.com/collections/order-of-the-baby-cannon-in-lieu-of-fun

that redirect is configured in _config.yml lines 14 to 19

### Which returns this configuration page/message:

Only one step left!
To finish setting up your new web address, go to [your domain settings](https://www.shopify.com/admin/settings/domains), click "Connect existing domain", and enter: revolutionartshop.com

### Is Shopify configured for  this?

My best guess is that the shopify site is not configured or misconfigured.

**Comment by creachadair** [comment]
Hi, @tomrake, thanks for the report. It looks like something got broken in our Revolution shop config, since that link was working just a couple weeks ago.

@JBordeaux2020 Do you still have charge of the shop site?

**Comment by creachadair** [comment]
> MF, Apologies, the shop has closed. We need to remove the merch links. jb

Ok, thanks for the update, will do! Sorry I had missed that change.

**Comment by creachadair** [comment]
I removed the links and redirects in 9956cf0, which should fix the site once the ongoing GitHub Actions incident is resolved and the update goes through. Thanks again for letting us know.
