### ISSUE TITLE
Navigation menu does not show up in Safari Reader mode on iPad

### ISSUE THREAD

**Issue by creachadair** [inlieuoffun/inlieuoffun.github.io#3]
Reported by @JBordeaux2020.

Specifically, the navigation bar at the top, which usually shows as a drop-down menu in Safari, is not appearing when rendered in Reader mode.

**Comment by creachadair** [comment]
As a workaround, I added links to the Episode Log and Guest List (the two items in the nav) to the main page (1c3bd407). That doesn't fix the problem but should at least let folks move around.

**Comment by creachadair** [comment]
I was able to reproduce this problem on an iPad running up-to-date iOS 13. It seems to be specific to the tablet layout, since the same version of Safari on an iPhone does not trigger the problem. Specifically: I can't even enable Reader mode for this site on the iPhone, whereas I can on the iPad.

**Comment by creachadair** [comment]
This issue appears related: https://github.com/jekyll/minima/issues/93. That issue notes that https://github.com/jekyll/minima/commit/e4c9d1ed589e411129d71f4693f24992f2acb63a disabled the popup for displays larger than a phone. That might explain why the menu doesn't show up on the iPad. But even if that's correct, I don't (yet) know why the nav elements that show on the desktop are not displayed.

**Comment by skandhurkat** [comment]
The navigation bar appears fine on Safari on my iPad running iOS 14. Has the issue been fixed in upstream Jekyll?

**Comment by creachadair** [comment]
> The navigation bar appears fine on Safari on my iPad running iOS 14. Has the issue been fixed in upstream Jekyll?

Good question—I don't have ready access to an iPad to check. @JBordeaux2020 are you still able to reproduce this problem?

**Comment by creachadair** [comment]
Closed as no longer reproducible. Feel free to re-open if it still occurs.
