### ISSUE TITLE
Maggie's Twitter account 

### ISSUE THREAD

**Issue by mcdy** [inlieuoffun/inlieuoffun.github.io#7]
The Guests page currently links to https://twitter.com/maggiecaroline for Maggie Feldman-Piltch

The Twitter account she actively uses these days is https://twitter.com/maggiecaroline1, which you can verify via this Tweet:  https://twitter.com/benjaminwittes/status/1250877941946474496

**Comment by creachadair** [comment]
Thank you, this is fixed in 0c21a871.

**Comment by mcdy** [comment]
So awesome. Thank you!
