### ISSUE TITLE
Missing Mona Charen in the guest list

### ISSUE THREAD

**Issue by skandhurkat** [inlieuoffun/inlieuoffun.github.io#9]
In [episode 198 at the 37:26 mark](https://youtu.be/XDVQ2N1sjvM?t=2246), Ben mentions Mona Charen as a prior guest. However, Mona Charen does not show up in the list of guests.

Since there isn't an episode on YouTube that lists Mona Charen in the title, I'm guessing that it must be a mystery guest episode, but I have not yet found it.

**Comment by creachadair** [comment]
He did say that, but I think he may be mistaken—the early site data came from a combination of files that @JBordeaux2020 and I compiled separately, and neither of those data sets has Mona Charen listed.

**Comment by creachadair** [comment]
I went back and listened to the clip more carefully, and I don't think we have a bug. Here is a (lightly-redacted) transcript of that moment:

> "There is an incredibly talented group of people, half of whom have been on the show, the Sarah Longwells and Tim Millers and Bill Kristols and Mona Charens, and Rick Wilson; you know, these are really talented Republican thinkers and operatives and activists."

I don't believe this list was meant to only be those folks who've come on the show. On that basis I'm going to close this issue, but if you find I've missed something please feel free to re-open it. Thanks for paying such close attention and for bringing up the question.
